version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  [
    lylehmann,
    cimdata,
    Cimdata,
    focusbuddy,
    brushbuddy,
    neurodivergent,
    neurodiverse,
    neurodiversity,
    Neurodiversity,
    omnichannel,
    tabler,
    Yair,
    WBSCS,
    linkedin,
    Linkedin,
    github,
    metacafe,
    saas,
    wireframing,
    Bildungsakademie,
    Hochschule,
    Studien,
    Universität,
    Heiligenstadt,
    Heilbad,
    Karls,
    Ruprecht,
    Jüdische,
    Kerem,
    Porfolio,
    impressum,
    Impressum,
    Innodata,
    Gispert,
    Lukas Lehmann,
  ]
ignoreWords: []
import: []
