version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bezier
  - Bildungsakademie
  - brushbuddy
  - cimdata
  - Cimdata
  - focusbuddy
  - Frontmatter
  - gemini
  - Gispert
  - github
  - Heilbad
  - Heiligenstadt
  - Hochschule
  - IIIF
  - impressum
  - Impressum
  - Innodata
  - Jüdische
  - junie
  - Karls
  - Kerem
  - linecap
  - linejoin
  - linkedin
  - Linkedin
  - Lukas Lehmann
  - lylehmann
  - metacafe
  - mozjpeg
  - neurodivergent
  - neurodiverse
  - neurodiversity
  - Neurodiversity
  - omnichannel
  - onwarn
  - Porfolio
  - Ruprecht
  - saas
  - Studien
  - tabler
  - Universität
  - vfile
  - WBSCS
  - wireframing
  - Yair
ignoreWords: []
import: []
