---
name: "prepare-release"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  pre-release:
    name: "Prepare Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write # Required to create releases and tags
      issues: write # Required to comment on issues
      pull-requests: write # Required to comment on PRs

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Next Release"
